language: python
python:
- '2.7'
install:
- pip install Flask WTForms
script:
- python -m unittest discover
notifications:
  slack:
    secure: RPQlZ47EQBm9Y8cvnGM7gMRcirujrE+zilHhmhLJSHnIJFhFUoeSPg9UTn8J40Q17X99JMuY/XAhKwOeqkBFlN/4HRVljP9RZw9tTx92+8b9lg5u/kOIWDv6mlrPFc8QYiHwgjjiatVRJaxjZRXmcQ23Y1l6i/SEvLoOVAshPR8jKyMoO6U7U7Y4nMHEuTz1vy4yxf5LUdkQSJyhNCSVjJTWHHc61ufsNBPQD7uXJ4loAIGwgboLbZ6RaAH/88rWDa5kT6wpf0/wx2sNZRZwv33Z3wEwRrTWXe6UNJZgFLSRAnxHs3GUEKY7xqd7CXOydHhzWWCAVPg+wg82eRhsz1ZT0l3htWWKhhfQ67D9rg1EO2snAIDvnqY6A0AAhC01YlSMaeXvZjZOkKi0f/xUzJ3+uxdYbF+UHeLWrPaYuRnHgt8CNYRfeG14IiO40OsNzzxzQa8O1kd16fvYmLP6yO+DYpgiW2cMQaVIx8f7/Dbttd/o8wYI07MMvchF3ineJv6Nqwp43y+w8L0zWrrQKm/5qlAzAxSrFjwvJe6FSs8OGm4HuNadV5V99wIEuc0S5wMk9ISsNg9gTy3ELmx7jmYhRQWkfiqd3ZKAPGdirOzVHcpAtxnTpHYcGtMZ9zs9l/3HcyX2t4rR2bwhJtO0v/EUYC2LR/Uz7Bx/ib5XPFc=
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: desolate-woodland-5931
  strategy: git